AtlasOfLivingAustralia/fieldcapture

- grails-app/views/home/index.gsp
- grails-app/views/report/_greenArmy.gsp
Fixed a bug with the ad hoc docs tab.
> Added green army report the home page.

- grails-app/views/project/index.gsp
Allowed end dates to be inferred from duration.
> Added actual project duration.

- grails-app/views/home/public.gsp
- grails-app/views/report/_statistics.gsp
- grails-app/views/shared/_blog.gsp
- grails-app/views/shared/_poi.gsp
> Minor html changes.

- grails-app/controllers/au/org/ala/merit/ProjectController.groovy
- grails-app/views/project/index.gsp
#	grails-app/controllers/au/org/ala/merit/ProjectController.groovy
#	grails-app/views/project/index.gsp
> Only publically display MERI plans if the plan is approved.

- grails-app/services/au/org/ala/merit/UserService.groovy
- src/main/groovy/au/org/ala/merit/CheckRisksAndThreatsTask.groovy
- src/main/groovy/au/org/ala/merit/StatisticsFactory.groovy
- src/test/groovy/au/org/ala/merit/CheckRisksAndThreatsTaskSpec.groovy
I was checking logs (for this amongst other OIDC changes) and found the scheduled risks and threats check failed due to authService.isUserInRole failing (because of the new ala-auth-plugin changes)
> Fix problem with scheduled risks task after oidc changes #2646

- grails-app/views/project/projectReport.gsp
- src/integration-test/groovy/pages/modules/EditableMeriPlan.groovy
- src/main/groovy/au/org/ala/merit/command/ProjectSummaryReportCommand.groovy
- src/test/groovy/au/org/ala/merit/ProjectSummaryReportCommandSpec.groovy
Note this PR has a dependency on the ecodata-client-plugin PR so that should be reviewed first.
> Fixing project summary for multiple versions of the same form #1841

- grails-app/views/shared/_editDocuments.gsp
Looks like I accidentally branched this off 2703 so I've issued the PR against 2703 to make the changes clear.
> Hide autogenerated documents #2757

- src/main/scripts/releases/2.10/adhoc/deleteDuplicateOutcomesReports.js
- src/main/scripts/utils/reports.js
Script has been run on staging you can compare to prod to test.   See related ticket.
> Script for #2800

- forms/rdp/rdpOutputReport.json
- gradle.properties
- grails-app/controllers/au/org/ala/merit/ProjectController.groovy
- grails-app/services/au/org/ala/merit/ProjectService.groovy
- grails-app/views/activity/activityReport.gsp
Hey @salomon-j this still has features that need to be implemented (ideally adding non string value support to the select2 bindings) but this version illustrates the behaviour I'd like to demonstrate.
> First cut of support for outcomes in Outputs Report #2940

- src/main/scripts/releases/3.2/insertParatooProtocolConfig.js
> Paratoo protocol config updates

- src/main/scripts/releases/3.2/insertParatooProtocolConfig.js
- remove start end date path from protocol config
> start end date fix for on-plot and off-plot protocols

- grails-app/controllers/au/org/ala/merit/HomeController.groovy
- src/main/groovy/au/org/ala/merit/reports/NHTOutputReportLifecycleListener.groovy
- src/main/groovy/au/org/ala/merit/reports/ReportLifecycleListener.groovy
- clear siteId from report activity and delete site #3102
> clear siteId from report activity and delete site

- grails-app/assets/javascripts/knockout-custom-bindings.js
- grails-app/assets/stylesheets/meriplan.css
- grails-app/views/project/meriPlanReadOnly/_extendedBaselineMonitoring.gsp
- grails-app/views/project/meriPlanReadOnly/_extendedKeyThreats.gsp
Probably the easiest way to test this one is to deploy to staging and look at the problem project printable MERI plan.
> Read only MERI formatting tweaks for #3230

- forms/mongo/insertParatooProtocolConfig.js
- species generation for Fauna Aerial Survey
> species generation for Fauna Aerial Survey

- gradle.properties
- grails-app/conf/application.groovy
- src/integration-test/resources/wiremock/mappings/oidcDiscovery.json
- updated scope to have deployment environment
- upgraded ala security plugin to 6.3.0-SNAPSHOT
> updated scope to have deployment environment #3265

- src/main/scripts/releases/4.0/node/updateGeographicInfoOfOldProjects.js
- update electorates/states of existing projects
> update electorates/states of existing projects #3292

- grails-app/assets/javascripts/projectExplorer.js
- grails-app/services/au/org/ala/merit/SearchService.groovy
- grails-app/views/home/_projectFinder.gsp
- package-lock.json
- package.json
- src/integration-test/groovy/au/org/ala/fieldcapture/ProjectExplorerSpec.groovy
- src/integration-test/groovy/pages/ProjectExplorer.groovy
- src/integration-test/groovy/pages/ReloadablePage.groovy
- src/integration-test/resources/dataset2/loadDataSet.js
- src/test/js/spec/DatePickerModelSpec.js
- start and end date behaviour modification
- added functional and unit test cases
> #3291 start and end date behaviour modification

- grails-app/assets/javascripts/projectExplorer.js
- grails-app/services/au/org/ala/merit/SearchService.groovy
- grails-app/views/home/_downloadAllAsXlsx.gsp
- grails-app/views/home/_projectFinder.gsp
- grails-app/views/shared/_sites.gsp
- src/main/groovy/au/org/ala/merit/DateUtils.groovy
- src/test/groovy/au/org/ala/merit/SearchServiceSpec.groovy
- src/test/js/spec/DatePickerModelSpec.js
> project explorer start date and end date with client timezone

- src/main/scripts/releases/4.1/adhoc/forceSelectFormVersionForReports.js
- update form version for reports
> #3343 update form version for reports

- grails-app/controllers/au/org/ala/merit/SiteController.groovy
- grails-app/services/au/org/ala/merit/ImportService.groovy
- grails-app/services/au/org/ala/merit/SiteService.groovy
- grails-app/services/au/org/ala/merit/SpatialService.groovy
- src/test/groovy/au/org/ala/merit/ImportServiceSpec.groovy
- src/test/groovy/au/org/ala/merit/SiteServiceSpec.groovy
- src/test/groovy/au/org/ala/merit/SpatialServiceSpec.groovy
- removed spatial portal from shape file upload
>  removed spatial portal from shape file upload #2789

- grails-app/assets/javascripts/projects.js
- grails-app/conf/application.groovy
- grails-app/controllers/au/org/ala/merit/ProjectController.groovy
- grails-app/services/au/org/ala/merit/ProjectService.groovy
- grails-app/views/project/_editProject.gsp
- grails-app/views/project/_geographicInfo.gsp
- grails-app/views/project/_overview.gsp
- grails-app/views/project/index.gsp
- ui to enter states/electorates manually and supporting code
> ui to enter states/electorates manually and supporting code #1724

- forms/other/regionalCapacityServicesReport.json
indigenous workforce participation changes
> indigenous workforce participation changes #3369

- src/main/groovy/au/org/ala/merit/command/MeriPlanReportCommand.groovy
https://support.ehelp.edu.au/a/tickets/224337
> Don't include activities in MERI plan reports #3423

- grails-app/views/home/_projectFinder.gsp
- src/integration-test/groovy/au/org/ala/fieldcapture/ImportProjectsSpec.groovy
- src/integration-test/groovy/au/org/ala/fieldcapture/ProjectExplorerSpec.groovy
- src/integration-test/groovy/au/org/ala/fieldcapture/StubbedCasSpec.groovy
- src/integration-test/groovy/pages/ProjectExplorer.groovy
- fix issue with date option check being cleared when checking facets item other than date
> #3467 - date facet issue

- grails-app/taglib/au/org/ala/merit/FCTagLib.groovy
- grails-app/views/project/meriPlanChanges/_extendedBaselineMonitoring.gsp
- grails-app/views/project/meriPlanChanges/_monitoringIndicators.gsp
You can reproduce the error here by adding a new baseline to any MERI plan then using the 'compare with latest version' button.  If you want to reproduce in prod, you can use the MERIT Monitor integration project.
> Fixed bug in changes in baseline section of plan #3533

- grails-app/services/au/org/ala/merit/UserService.groovy
Maybe hold off on this one until I hear back about the question I asked the team this morning.
> Tided hub role mapping #3527
